services:
  postgres:
    image: postgres:18-alpine
    container_name: area-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - area-net

  server:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - PUBLIC_BACKEND_API_URL=${PUBLIC_BACKEND_API_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    command: sh -c "sleep 5 && cd apps/backend && bunx prisma db push && bun run src/index.ts"
    networks:
      - area-net

  client_mobile:
    build:
      context: apps/mobile
      dockerfile: Dockerfile
    volumes:
      - apk-share:/dist
    networks:
      - area-net

  client_web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        PUBLIC_BACKEND_API_URL: ${PUBLIC_BACKEND_API_URL}
    ports:
      - "8081:8081"
    depends_on:
      - server
      - client_mobile
    volumes:
      - apk-share:/app/apps/web/static/apk
    networks:
      - area-net

volumes:
  db-data:
  apk-share:

networks:
  area-net:
    driver: bridge
