name: CI - Area

on:
  push:
    branches: ["main", "dev", "workflow/CI-CD"]
  pull_request:
    branches: ["main", "dev", "workflow/CI-CD"]

jobs:
  # test le backend avec elysia et prisma
  backend-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Installer Dépendances Globales
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/test_db
        run: bun install

      - name: Push DB Schema
        working-directory: ./apps/backend
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/test_db
        run: bun run prisma db push

      # - name: Lint Backend
      #   working-directory: ./apps/backend
      #   run: bun run lint
      #   continue-on-error: true

      - name: Test Backend
        working-directory: ./apps/backend
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/test_db
        run: bun test

  # vérifier le frontend
  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Installer les dépendances
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
        run: bun install

      # - name: Vérifier le Lint Frontend
      #   working-directory: ./apps/web
      #   run: bun run lint
      #   continue-on-error: true

      - name: Vérifier le Build
        working-directory: ./
        env:
          PUBLIC_BACKEND_API_URL: https://api.placeholder.com
        run: bun run build

  docker-check:
    runs-on: ubuntu-latest
    needs: [backend-check, frontend-check]
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Create the .env file
        run: |
          echo "POSTGRES_USER=user" >> .env
          echo "POSTGRES_PASSWORD=password" >> .env
          echo "POSTGRES_DB=area" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "DATABASE_URL=postgresql://user:password@postgres:5432/area" >> .env
          echo "PUBLIC_BACKEND_API_URL=http://localhost:8080" >> .env

      - name: test the docker build
        run: docker compose build
